// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Gopher Market Loyalty System API
//
//	API for user registration, authentication and order management
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//	  - text/plain
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
