// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "API for user registration, authentication and order management",
    "title": "Gopher Market Loyalty System API",
    "version": "1.0.0"
  },
  "paths": {
    "/api/user/balance": {
      "get": {
        "security": [
          {
            "cookieAuth": []
          },
          {
            "bearerAuth": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Balance"
        ],
        "summary": "Get current user balance",
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "$ref": "#/definitions/Balance"
            }
          },
          "401": {
            "description": "User not authenticated"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/user/balance/withdraw": {
      "post": {
        "security": [
          {
            "cookieAuth": []
          },
          {
            "bearerAuth": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Balance"
        ],
        "summary": "Withdraw funds from balance",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/WithdrawalRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Withdrawal successful"
          },
          "401": {
            "description": "User not authenticated"
          },
          "402": {
            "description": "Insufficient funds"
          },
          "422": {
            "description": "Invalid order number"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/user/login": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "User"
        ],
        "summary": "Authenticate user",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserCredentials"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User successfully authenticated",
            "headers": {
              "Authorization": {
                "type": "string",
                "description": "Authorization token"
              },
              "Set-Cookie": {
                "type": "string",
                "description": "Session cookie"
              }
            }
          },
          "400": {
            "description": "Invalid request format"
          },
          "401": {
            "description": "Invalid login/password pair"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/user/orders": {
      "get": {
        "security": [
          {
            "cookieAuth": []
          },
          {
            "bearerAuth": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Get list of uploaded order numbers",
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Order"
              }
            }
          },
          "204": {
            "description": "No data available"
          },
          "401": {
            "description": "User not authenticated"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "post": {
        "security": [
          {
            "cookieAuth": []
          },
          {
            "bearerAuth": []
          }
        ],
        "consumes": [
          "text/plain"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Upload order number",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string",
              "example": "12345678903"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Order number was already uploaded by this user"
          },
          "202": {
            "description": "New order number accepted for processing"
          },
          "400": {
            "description": "Invalid request format"
          },
          "401": {
            "description": "User not authenticated"
          },
          "409": {
            "description": "Order number was already uploaded by another user"
          },
          "422": {
            "description": "Invalid order number format"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/user/register": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "User"
        ],
        "summary": "Register a new user",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserCredentials"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User successfully registered and authenticated",
            "headers": {
              "Authorization": {
                "type": "string",
                "description": "Authorization token"
              },
              "Set-Cookie": {
                "type": "string",
                "description": "Session cookie"
              }
            }
          },
          "400": {
            "description": "Invalid request format"
          },
          "409": {
            "description": "Login already taken"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/user/withdrawals": {
      "get": {
        "security": [
          {
            "cookieAuth": []
          },
          {
            "bearerAuth": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Balance"
        ],
        "summary": "Get withdrawal history",
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Withdrawal"
              }
            }
          },
          "204": {
            "description": "No withdrawals yet"
          },
          "401": {
            "description": "User not authenticated"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Balance": {
      "type": "object",
      "properties": {
        "current": {
          "type": "number",
          "example": 500.5
        },
        "withdrawn": {
          "type": "number",
          "example": 42
        }
      }
    },
    "Order": {
      "type": "object",
      "properties": {
        "accrual": {
          "type": "number",
          "example": 500
        },
        "number": {
          "type": "string",
          "example": "9278923470"
        },
        "status": {
          "type": "string",
          "enum": [
            "NEW",
            "PROCESSING",
            "INVALID",
            "PROCESSED"
          ],
          "example": "PROCESSED"
        },
        "uploaded_at": {
          "type": "string",
          "format": "date-time",
          "example": "2020-12-10T15:15:45+03:00"
        }
      }
    },
    "UserCredentials": {
      "type": "object",
      "required": [
        "login",
        "password"
      ],
      "properties": {
        "login": {
          "type": "string",
          "example": "user123"
        },
        "password": {
          "type": "string",
          "example": "securepassword"
        }
      }
    },
    "Withdrawal": {
      "type": "object",
      "properties": {
        "order": {
          "type": "string",
          "example": "2377225624"
        },
        "processed_at": {
          "type": "string",
          "format": "date-time",
          "example": "2020-12-09T16:09:57+03:00"
        },
        "sum": {
          "type": "number",
          "example": 500
        }
      }
    },
    "WithdrawalRequest": {
      "type": "object",
      "required": [
        "order",
        "sum"
      ],
      "properties": {
        "order": {
          "type": "string",
          "example": "2377225624"
        },
        "sum": {
          "type": "number",
          "example": 751
        }
      }
    }
  },
  "securityDefinitions": {
    "bearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    },
    "cookieAuth": {
      "type": "apiKey",
      "name": "Cookie",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "API for user registration, authentication and order management",
    "title": "Gopher Market Loyalty System API",
    "version": "1.0.0"
  },
  "paths": {
    "/api/user/balance": {
      "get": {
        "security": [
          {
            "cookieAuth": []
          },
          {
            "bearerAuth": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Balance"
        ],
        "summary": "Get current user balance",
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "$ref": "#/definitions/Balance"
            }
          },
          "401": {
            "description": "User not authenticated"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/user/balance/withdraw": {
      "post": {
        "security": [
          {
            "cookieAuth": []
          },
          {
            "bearerAuth": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Balance"
        ],
        "summary": "Withdraw funds from balance",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/WithdrawalRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Withdrawal successful"
          },
          "401": {
            "description": "User not authenticated"
          },
          "402": {
            "description": "Insufficient funds"
          },
          "422": {
            "description": "Invalid order number"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/user/login": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "User"
        ],
        "summary": "Authenticate user",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserCredentials"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User successfully authenticated",
            "headers": {
              "Authorization": {
                "type": "string",
                "description": "Authorization token"
              },
              "Set-Cookie": {
                "type": "string",
                "description": "Session cookie"
              }
            }
          },
          "400": {
            "description": "Invalid request format"
          },
          "401": {
            "description": "Invalid login/password pair"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/user/orders": {
      "get": {
        "security": [
          {
            "cookieAuth": []
          },
          {
            "bearerAuth": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Get list of uploaded order numbers",
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Order"
              }
            }
          },
          "204": {
            "description": "No data available"
          },
          "401": {
            "description": "User not authenticated"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "post": {
        "security": [
          {
            "cookieAuth": []
          },
          {
            "bearerAuth": []
          }
        ],
        "consumes": [
          "text/plain"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Upload order number",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string",
              "example": "12345678903"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Order number was already uploaded by this user"
          },
          "202": {
            "description": "New order number accepted for processing"
          },
          "400": {
            "description": "Invalid request format"
          },
          "401": {
            "description": "User not authenticated"
          },
          "409": {
            "description": "Order number was already uploaded by another user"
          },
          "422": {
            "description": "Invalid order number format"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/user/register": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "User"
        ],
        "summary": "Register a new user",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserCredentials"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User successfully registered and authenticated",
            "headers": {
              "Authorization": {
                "type": "string",
                "description": "Authorization token"
              },
              "Set-Cookie": {
                "type": "string",
                "description": "Session cookie"
              }
            }
          },
          "400": {
            "description": "Invalid request format"
          },
          "409": {
            "description": "Login already taken"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/user/withdrawals": {
      "get": {
        "security": [
          {
            "cookieAuth": []
          },
          {
            "bearerAuth": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Balance"
        ],
        "summary": "Get withdrawal history",
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Withdrawal"
              }
            }
          },
          "204": {
            "description": "No withdrawals yet"
          },
          "401": {
            "description": "User not authenticated"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Balance": {
      "type": "object",
      "properties": {
        "current": {
          "type": "number",
          "example": 500.5
        },
        "withdrawn": {
          "type": "number",
          "example": 42
        }
      }
    },
    "Order": {
      "type": "object",
      "properties": {
        "accrual": {
          "type": "number",
          "example": 500
        },
        "number": {
          "type": "string",
          "example": "9278923470"
        },
        "status": {
          "type": "string",
          "enum": [
            "NEW",
            "PROCESSING",
            "INVALID",
            "PROCESSED"
          ],
          "example": "PROCESSED"
        },
        "uploaded_at": {
          "type": "string",
          "format": "date-time",
          "example": "2020-12-10T15:15:45+03:00"
        }
      }
    },
    "UserCredentials": {
      "type": "object",
      "required": [
        "login",
        "password"
      ],
      "properties": {
        "login": {
          "type": "string",
          "example": "user123"
        },
        "password": {
          "type": "string",
          "example": "securepassword"
        }
      }
    },
    "Withdrawal": {
      "type": "object",
      "properties": {
        "order": {
          "type": "string",
          "example": "2377225624"
        },
        "processed_at": {
          "type": "string",
          "format": "date-time",
          "example": "2020-12-09T16:09:57+03:00"
        },
        "sum": {
          "type": "number",
          "example": 500
        }
      }
    },
    "WithdrawalRequest": {
      "type": "object",
      "required": [
        "order",
        "sum"
      ],
      "properties": {
        "order": {
          "type": "string",
          "example": "2377225624"
        },
        "sum": {
          "type": "number",
          "example": 751
        }
      }
    }
  },
  "securityDefinitions": {
    "bearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    },
    "cookieAuth": {
      "type": "apiKey",
      "name": "Cookie",
      "in": "header"
    }
  }
}`))
}
