// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAPIUserOrdersHandlerFunc turns a function with the right signature into a get API user orders handler
type GetAPIUserOrdersHandlerFunc func(GetAPIUserOrdersParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAPIUserOrdersHandlerFunc) Handle(params GetAPIUserOrdersParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAPIUserOrdersHandler interface for that can handle valid get API user orders params
type GetAPIUserOrdersHandler interface {
	Handle(GetAPIUserOrdersParams, interface{}) middleware.Responder
}

// NewGetAPIUserOrders creates a new http.Handler for the get API user orders operation
func NewGetAPIUserOrders(ctx *middleware.Context, handler GetAPIUserOrdersHandler) *GetAPIUserOrders {
	return &GetAPIUserOrders{Context: ctx, Handler: handler}
}

/*
	GetAPIUserOrders swagger:route GET /api/user/orders Orders getApiUserOrders

Get list of uploaded order numbers
*/
type GetAPIUserOrders struct {
	Context *middleware.Context
	Handler GetAPIUserOrdersHandler
}

func (o *GetAPIUserOrders) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAPIUserOrdersParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
