// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/DanilNaum/gophermarket/internal/api/models"
)

// GetAPIUserOrdersOKCode is the HTTP code returned for type GetAPIUserOrdersOK
const GetAPIUserOrdersOKCode int = 200

/*
GetAPIUserOrdersOK Successful response

swagger:response getApiUserOrdersOK
*/
type GetAPIUserOrdersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Order `json:"body,omitempty"`
}

// NewGetAPIUserOrdersOK creates GetAPIUserOrdersOK with default headers values
func NewGetAPIUserOrdersOK() *GetAPIUserOrdersOK {

	return &GetAPIUserOrdersOK{}
}

// WithPayload adds the payload to the get Api user orders o k response
func (o *GetAPIUserOrdersOK) WithPayload(payload []*models.Order) *GetAPIUserOrdersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api user orders o k response
func (o *GetAPIUserOrdersOK) SetPayload(payload []*models.Order) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIUserOrdersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Order, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAPIUserOrdersNoContentCode is the HTTP code returned for type GetAPIUserOrdersNoContent
const GetAPIUserOrdersNoContentCode int = 204

/*
GetAPIUserOrdersNoContent No data available

swagger:response getApiUserOrdersNoContent
*/
type GetAPIUserOrdersNoContent struct {
}

// NewGetAPIUserOrdersNoContent creates GetAPIUserOrdersNoContent with default headers values
func NewGetAPIUserOrdersNoContent() *GetAPIUserOrdersNoContent {

	return &GetAPIUserOrdersNoContent{}
}

// WriteResponse to the client
func (o *GetAPIUserOrdersNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetAPIUserOrdersUnauthorizedCode is the HTTP code returned for type GetAPIUserOrdersUnauthorized
const GetAPIUserOrdersUnauthorizedCode int = 401

/*
GetAPIUserOrdersUnauthorized User not authenticated

swagger:response getApiUserOrdersUnauthorized
*/
type GetAPIUserOrdersUnauthorized struct {
}

// NewGetAPIUserOrdersUnauthorized creates GetAPIUserOrdersUnauthorized with default headers values
func NewGetAPIUserOrdersUnauthorized() *GetAPIUserOrdersUnauthorized {

	return &GetAPIUserOrdersUnauthorized{}
}

// WriteResponse to the client
func (o *GetAPIUserOrdersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetAPIUserOrdersInternalServerErrorCode is the HTTP code returned for type GetAPIUserOrdersInternalServerError
const GetAPIUserOrdersInternalServerErrorCode int = 500

/*
GetAPIUserOrdersInternalServerError Internal server error

swagger:response getApiUserOrdersInternalServerError
*/
type GetAPIUserOrdersInternalServerError struct {
}

// NewGetAPIUserOrdersInternalServerError creates GetAPIUserOrdersInternalServerError with default headers values
func NewGetAPIUserOrdersInternalServerError() *GetAPIUserOrdersInternalServerError {

	return &GetAPIUserOrdersInternalServerError{}
}

// WriteResponse to the client
func (o *GetAPIUserOrdersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
