// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAPIUserOrdersOKCode is the HTTP code returned for type PostAPIUserOrdersOK
const PostAPIUserOrdersOKCode int = 200

/*
PostAPIUserOrdersOK Order number was already uploaded by this user

swagger:response postApiUserOrdersOK
*/
type PostAPIUserOrdersOK struct {
}

// NewPostAPIUserOrdersOK creates PostAPIUserOrdersOK with default headers values
func NewPostAPIUserOrdersOK() *PostAPIUserOrdersOK {

	return &PostAPIUserOrdersOK{}
}

// WriteResponse to the client
func (o *PostAPIUserOrdersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostAPIUserOrdersAcceptedCode is the HTTP code returned for type PostAPIUserOrdersAccepted
const PostAPIUserOrdersAcceptedCode int = 202

/*
PostAPIUserOrdersAccepted New order number accepted for processing

swagger:response postApiUserOrdersAccepted
*/
type PostAPIUserOrdersAccepted struct {
}

// NewPostAPIUserOrdersAccepted creates PostAPIUserOrdersAccepted with default headers values
func NewPostAPIUserOrdersAccepted() *PostAPIUserOrdersAccepted {

	return &PostAPIUserOrdersAccepted{}
}

// WriteResponse to the client
func (o *PostAPIUserOrdersAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(202)
}

// PostAPIUserOrdersBadRequestCode is the HTTP code returned for type PostAPIUserOrdersBadRequest
const PostAPIUserOrdersBadRequestCode int = 400

/*
PostAPIUserOrdersBadRequest Invalid request format

swagger:response postApiUserOrdersBadRequest
*/
type PostAPIUserOrdersBadRequest struct {
}

// NewPostAPIUserOrdersBadRequest creates PostAPIUserOrdersBadRequest with default headers values
func NewPostAPIUserOrdersBadRequest() *PostAPIUserOrdersBadRequest {

	return &PostAPIUserOrdersBadRequest{}
}

// WriteResponse to the client
func (o *PostAPIUserOrdersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostAPIUserOrdersUnauthorizedCode is the HTTP code returned for type PostAPIUserOrdersUnauthorized
const PostAPIUserOrdersUnauthorizedCode int = 401

/*
PostAPIUserOrdersUnauthorized User not authenticated

swagger:response postApiUserOrdersUnauthorized
*/
type PostAPIUserOrdersUnauthorized struct {
}

// NewPostAPIUserOrdersUnauthorized creates PostAPIUserOrdersUnauthorized with default headers values
func NewPostAPIUserOrdersUnauthorized() *PostAPIUserOrdersUnauthorized {

	return &PostAPIUserOrdersUnauthorized{}
}

// WriteResponse to the client
func (o *PostAPIUserOrdersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostAPIUserOrdersConflictCode is the HTTP code returned for type PostAPIUserOrdersConflict
const PostAPIUserOrdersConflictCode int = 409

/*
PostAPIUserOrdersConflict Order number was already uploaded by another user

swagger:response postApiUserOrdersConflict
*/
type PostAPIUserOrdersConflict struct {
}

// NewPostAPIUserOrdersConflict creates PostAPIUserOrdersConflict with default headers values
func NewPostAPIUserOrdersConflict() *PostAPIUserOrdersConflict {

	return &PostAPIUserOrdersConflict{}
}

// WriteResponse to the client
func (o *PostAPIUserOrdersConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// PostAPIUserOrdersUnprocessableEntityCode is the HTTP code returned for type PostAPIUserOrdersUnprocessableEntity
const PostAPIUserOrdersUnprocessableEntityCode int = 422

/*
PostAPIUserOrdersUnprocessableEntity Invalid order number format

swagger:response postApiUserOrdersUnprocessableEntity
*/
type PostAPIUserOrdersUnprocessableEntity struct {
}

// NewPostAPIUserOrdersUnprocessableEntity creates PostAPIUserOrdersUnprocessableEntity with default headers values
func NewPostAPIUserOrdersUnprocessableEntity() *PostAPIUserOrdersUnprocessableEntity {

	return &PostAPIUserOrdersUnprocessableEntity{}
}

// WriteResponse to the client
func (o *PostAPIUserOrdersUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}

// PostAPIUserOrdersInternalServerErrorCode is the HTTP code returned for type PostAPIUserOrdersInternalServerError
const PostAPIUserOrdersInternalServerErrorCode int = 500

/*
PostAPIUserOrdersInternalServerError Internal server error

swagger:response postApiUserOrdersInternalServerError
*/
type PostAPIUserOrdersInternalServerError struct {
}

// NewPostAPIUserOrdersInternalServerError creates PostAPIUserOrdersInternalServerError with default headers values
func NewPostAPIUserOrdersInternalServerError() *PostAPIUserOrdersInternalServerError {

	return &PostAPIUserOrdersInternalServerError{}
}

// WriteResponse to the client
func (o *PostAPIUserOrdersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
