// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostAPIUserOrdersHandlerFunc turns a function with the right signature into a post API user orders handler
type PostAPIUserOrdersHandlerFunc func(PostAPIUserOrdersParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAPIUserOrdersHandlerFunc) Handle(params PostAPIUserOrdersParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostAPIUserOrdersHandler interface for that can handle valid post API user orders params
type PostAPIUserOrdersHandler interface {
	Handle(PostAPIUserOrdersParams, interface{}) middleware.Responder
}

// NewPostAPIUserOrders creates a new http.Handler for the post API user orders operation
func NewPostAPIUserOrders(ctx *middleware.Context, handler PostAPIUserOrdersHandler) *PostAPIUserOrders {
	return &PostAPIUserOrders{Context: ctx, Handler: handler}
}

/*
	PostAPIUserOrders swagger:route POST /api/user/orders Orders postApiUserOrders

Upload order number
*/
type PostAPIUserOrders struct {
	Context *middleware.Context
	Handler PostAPIUserOrdersHandler
}

func (o *PostAPIUserOrders) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAPIUserOrdersParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
