// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Order order
//
// swagger:model Order
type Order struct {

	// accrual
	// Example: 500
	Accrual float64 `json:"accrual,omitempty"`

	// number
	// Example: 9278923470
	Number string `json:"number,omitempty"`

	// status
	// Example: PROCESSED
	// Enum: ["NEW","PROCESSING","INVALID","PROCESSED"]
	Status string `json:"status,omitempty"`

	// uploaded at
	// Example: 2020-12-10T15:15:45+03:00
	// Format: date-time
	UploadedAt strfmt.DateTime `json:"uploaded_at,omitempty"`
}

// Validate validates this order
func (m *Order) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUploadedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var orderTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["NEW","PROCESSING","INVALID","PROCESSED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderTypeStatusPropEnum = append(orderTypeStatusPropEnum, v)
	}
}

const (

	// OrderStatusNEW captures enum value "NEW"
	OrderStatusNEW string = "NEW"

	// OrderStatusPROCESSING captures enum value "PROCESSING"
	OrderStatusPROCESSING string = "PROCESSING"

	// OrderStatusINVALID captures enum value "INVALID"
	OrderStatusINVALID string = "INVALID"

	// OrderStatusPROCESSED captures enum value "PROCESSED"
	OrderStatusPROCESSED string = "PROCESSED"
)

// prop value enum
func (m *Order) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, orderTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Order) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

func (m *Order) validateUploadedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.UploadedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("uploaded_at", "body", "date-time", m.UploadedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this order based on context it is used
func (m *Order) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Order) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Order) UnmarshalBinary(b []byte) error {
	var res Order
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
