// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WithdrawalRequest withdrawal request
//
// swagger:model WithdrawalRequest
type WithdrawalRequest struct {

	// order
	// Example: 2377225624
	// Required: true
	Order *string `json:"order"`

	// sum
	// Example: 751
	// Required: true
	Sum *float64 `json:"sum"`
}

// Validate validates this withdrawal request
func (m *WithdrawalRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrder(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSum(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WithdrawalRequest) validateOrder(formats strfmt.Registry) error {

	if err := validate.Required("order", "body", m.Order); err != nil {
		return err
	}

	return nil
}

func (m *WithdrawalRequest) validateSum(formats strfmt.Registry) error {

	if err := validate.Required("sum", "body", m.Sum); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this withdrawal request based on context it is used
func (m *WithdrawalRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WithdrawalRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WithdrawalRequest) UnmarshalBinary(b []byte) error {
	var res WithdrawalRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
