// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Withdrawal withdrawal
//
// swagger:model Withdrawal
type Withdrawal struct {

	// order
	// Example: 2377225624
	Order string `json:"order,omitempty"`

	// processed at
	// Example: 2020-12-09T16:09:57+03:00
	// Format: date-time
	ProcessedAt strfmt.DateTime `json:"processed_at,omitempty"`

	// sum
	// Example: 500
	Sum float64 `json:"sum,omitempty"`
}

// Validate validates this withdrawal
func (m *Withdrawal) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProcessedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Withdrawal) validateProcessedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.ProcessedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("processed_at", "body", "date-time", m.ProcessedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this withdrawal based on context it is used
func (m *Withdrawal) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Withdrawal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Withdrawal) UnmarshalBinary(b []byte) error {
	var res Withdrawal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
