
ALTER TABLE withdrawal 
ALTER COLUMN processed_at TYPE TIMESTAMP WITH TIME ZONE,
ALTER COLUMN processed_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE orders 
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users 
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;