// Code generated by go-swagger; DO NOT EDIT.

package balance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/DanilNaum/gophermarket/internal/api/models"
)

// GetAPIUserBalanceOKCode is the HTTP code returned for type GetAPIUserBalanceOK
const GetAPIUserBalanceOKCode int = 200

/*
GetAPIUserBalanceOK Successful response

swagger:response getApiUserBalanceOK
*/
type GetAPIUserBalanceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Balance `json:"body,omitempty"`
}

// NewGetAPIUserBalanceOK creates GetAPIUserBalanceOK with default headers values
func NewGetAPIUserBalanceOK() *GetAPIUserBalanceOK {

	return &GetAPIUserBalanceOK{}
}

// WithPayload adds the payload to the get Api user balance o k response
func (o *GetAPIUserBalanceOK) WithPayload(payload *models.Balance) *GetAPIUserBalanceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api user balance o k response
func (o *GetAPIUserBalanceOK) SetPayload(payload *models.Balance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIUserBalanceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAPIUserBalanceUnauthorizedCode is the HTTP code returned for type GetAPIUserBalanceUnauthorized
const GetAPIUserBalanceUnauthorizedCode int = 401

/*
GetAPIUserBalanceUnauthorized User not authenticated

swagger:response getApiUserBalanceUnauthorized
*/
type GetAPIUserBalanceUnauthorized struct {
}

// NewGetAPIUserBalanceUnauthorized creates GetAPIUserBalanceUnauthorized with default headers values
func NewGetAPIUserBalanceUnauthorized() *GetAPIUserBalanceUnauthorized {

	return &GetAPIUserBalanceUnauthorized{}
}

// WriteResponse to the client
func (o *GetAPIUserBalanceUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetAPIUserBalanceInternalServerErrorCode is the HTTP code returned for type GetAPIUserBalanceInternalServerError
const GetAPIUserBalanceInternalServerErrorCode int = 500

/*
GetAPIUserBalanceInternalServerError Internal server error

swagger:response getApiUserBalanceInternalServerError
*/
type GetAPIUserBalanceInternalServerError struct {
}

// NewGetAPIUserBalanceInternalServerError creates GetAPIUserBalanceInternalServerError with default headers values
func NewGetAPIUserBalanceInternalServerError() *GetAPIUserBalanceInternalServerError {

	return &GetAPIUserBalanceInternalServerError{}
}

// WriteResponse to the client
func (o *GetAPIUserBalanceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
