// Code generated by go-swagger; DO NOT EDIT.

package balance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/DanilNaum/gophermarket/internal/api/models"
)

// GetAPIUserWithdrawalsOKCode is the HTTP code returned for type GetAPIUserWithdrawalsOK
const GetAPIUserWithdrawalsOKCode int = 200

/*
GetAPIUserWithdrawalsOK Successful response

swagger:response getApiUserWithdrawalsOK
*/
type GetAPIUserWithdrawalsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Withdrawal `json:"body,omitempty"`
}

// NewGetAPIUserWithdrawalsOK creates GetAPIUserWithdrawalsOK with default headers values
func NewGetAPIUserWithdrawalsOK() *GetAPIUserWithdrawalsOK {

	return &GetAPIUserWithdrawalsOK{}
}

// WithPayload adds the payload to the get Api user withdrawals o k response
func (o *GetAPIUserWithdrawalsOK) WithPayload(payload []*models.Withdrawal) *GetAPIUserWithdrawalsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api user withdrawals o k response
func (o *GetAPIUserWithdrawalsOK) SetPayload(payload []*models.Withdrawal) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIUserWithdrawalsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Withdrawal, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAPIUserWithdrawalsNoContentCode is the HTTP code returned for type GetAPIUserWithdrawalsNoContent
const GetAPIUserWithdrawalsNoContentCode int = 204

/*
GetAPIUserWithdrawalsNoContent No withdrawals yet

swagger:response getApiUserWithdrawalsNoContent
*/
type GetAPIUserWithdrawalsNoContent struct {
}

// NewGetAPIUserWithdrawalsNoContent creates GetAPIUserWithdrawalsNoContent with default headers values
func NewGetAPIUserWithdrawalsNoContent() *GetAPIUserWithdrawalsNoContent {

	return &GetAPIUserWithdrawalsNoContent{}
}

// WriteResponse to the client
func (o *GetAPIUserWithdrawalsNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetAPIUserWithdrawalsUnauthorizedCode is the HTTP code returned for type GetAPIUserWithdrawalsUnauthorized
const GetAPIUserWithdrawalsUnauthorizedCode int = 401

/*
GetAPIUserWithdrawalsUnauthorized User not authenticated

swagger:response getApiUserWithdrawalsUnauthorized
*/
type GetAPIUserWithdrawalsUnauthorized struct {
}

// NewGetAPIUserWithdrawalsUnauthorized creates GetAPIUserWithdrawalsUnauthorized with default headers values
func NewGetAPIUserWithdrawalsUnauthorized() *GetAPIUserWithdrawalsUnauthorized {

	return &GetAPIUserWithdrawalsUnauthorized{}
}

// WriteResponse to the client
func (o *GetAPIUserWithdrawalsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetAPIUserWithdrawalsInternalServerErrorCode is the HTTP code returned for type GetAPIUserWithdrawalsInternalServerError
const GetAPIUserWithdrawalsInternalServerErrorCode int = 500

/*
GetAPIUserWithdrawalsInternalServerError Internal server error

swagger:response getApiUserWithdrawalsInternalServerError
*/
type GetAPIUserWithdrawalsInternalServerError struct {
}

// NewGetAPIUserWithdrawalsInternalServerError creates GetAPIUserWithdrawalsInternalServerError with default headers values
func NewGetAPIUserWithdrawalsInternalServerError() *GetAPIUserWithdrawalsInternalServerError {

	return &GetAPIUserWithdrawalsInternalServerError{}
}

// WriteResponse to the client
func (o *GetAPIUserWithdrawalsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
