// Code generated by go-swagger; DO NOT EDIT.

package balance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAPIUserBalanceHandlerFunc turns a function with the right signature into a get API user balance handler
type GetAPIUserBalanceHandlerFunc func(GetAPIUserBalanceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAPIUserBalanceHandlerFunc) Handle(params GetAPIUserBalanceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAPIUserBalanceHandler interface for that can handle valid get API user balance params
type GetAPIUserBalanceHandler interface {
	Handle(GetAPIUserBalanceParams, interface{}) middleware.Responder
}

// NewGetAPIUserBalance creates a new http.Handler for the get API user balance operation
func NewGetAPIUserBalance(ctx *middleware.Context, handler GetAPIUserBalanceHandler) *GetAPIUserBalance {
	return &GetAPIUserBalance{Context: ctx, Handler: handler}
}

/*
	GetAPIUserBalance swagger:route GET /api/user/balance Balance getApiUserBalance

Get current user balance
*/
type GetAPIUserBalance struct {
	Context *middleware.Context
	Handler GetAPIUserBalanceHandler
}

func (o *GetAPIUserBalance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAPIUserBalanceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
