// Code generated by go-swagger; DO NOT EDIT.

package balance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAPIUserWithdrawalsHandlerFunc turns a function with the right signature into a get API user withdrawals handler
type GetAPIUserWithdrawalsHandlerFunc func(GetAPIUserWithdrawalsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAPIUserWithdrawalsHandlerFunc) Handle(params GetAPIUserWithdrawalsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAPIUserWithdrawalsHandler interface for that can handle valid get API user withdrawals params
type GetAPIUserWithdrawalsHandler interface {
	Handle(GetAPIUserWithdrawalsParams, interface{}) middleware.Responder
}

// NewGetAPIUserWithdrawals creates a new http.Handler for the get API user withdrawals operation
func NewGetAPIUserWithdrawals(ctx *middleware.Context, handler GetAPIUserWithdrawalsHandler) *GetAPIUserWithdrawals {
	return &GetAPIUserWithdrawals{Context: ctx, Handler: handler}
}

/*
	GetAPIUserWithdrawals swagger:route GET /api/user/withdrawals Balance getApiUserWithdrawals

Get withdrawal history
*/
type GetAPIUserWithdrawals struct {
	Context *middleware.Context
	Handler GetAPIUserWithdrawalsHandler
}

func (o *GetAPIUserWithdrawals) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAPIUserWithdrawalsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
