// Code generated by go-swagger; DO NOT EDIT.

package balance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAPIUserBalanceWithdrawOKCode is the HTTP code returned for type PostAPIUserBalanceWithdrawOK
const PostAPIUserBalanceWithdrawOKCode int = 200

/*
PostAPIUserBalanceWithdrawOK Withdrawal successful

swagger:response postApiUserBalanceWithdrawOK
*/
type PostAPIUserBalanceWithdrawOK struct {
}

// NewPostAPIUserBalanceWithdrawOK creates PostAPIUserBalanceWithdrawOK with default headers values
func NewPostAPIUserBalanceWithdrawOK() *PostAPIUserBalanceWithdrawOK {

	return &PostAPIUserBalanceWithdrawOK{}
}

// WriteResponse to the client
func (o *PostAPIUserBalanceWithdrawOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostAPIUserBalanceWithdrawUnauthorizedCode is the HTTP code returned for type PostAPIUserBalanceWithdrawUnauthorized
const PostAPIUserBalanceWithdrawUnauthorizedCode int = 401

/*
PostAPIUserBalanceWithdrawUnauthorized User not authenticated

swagger:response postApiUserBalanceWithdrawUnauthorized
*/
type PostAPIUserBalanceWithdrawUnauthorized struct {
}

// NewPostAPIUserBalanceWithdrawUnauthorized creates PostAPIUserBalanceWithdrawUnauthorized with default headers values
func NewPostAPIUserBalanceWithdrawUnauthorized() *PostAPIUserBalanceWithdrawUnauthorized {

	return &PostAPIUserBalanceWithdrawUnauthorized{}
}

// WriteResponse to the client
func (o *PostAPIUserBalanceWithdrawUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostAPIUserBalanceWithdrawPaymentRequiredCode is the HTTP code returned for type PostAPIUserBalanceWithdrawPaymentRequired
const PostAPIUserBalanceWithdrawPaymentRequiredCode int = 402

/*
PostAPIUserBalanceWithdrawPaymentRequired Insufficient funds

swagger:response postApiUserBalanceWithdrawPaymentRequired
*/
type PostAPIUserBalanceWithdrawPaymentRequired struct {
}

// NewPostAPIUserBalanceWithdrawPaymentRequired creates PostAPIUserBalanceWithdrawPaymentRequired with default headers values
func NewPostAPIUserBalanceWithdrawPaymentRequired() *PostAPIUserBalanceWithdrawPaymentRequired {

	return &PostAPIUserBalanceWithdrawPaymentRequired{}
}

// WriteResponse to the client
func (o *PostAPIUserBalanceWithdrawPaymentRequired) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(402)
}

// PostAPIUserBalanceWithdrawUnprocessableEntityCode is the HTTP code returned for type PostAPIUserBalanceWithdrawUnprocessableEntity
const PostAPIUserBalanceWithdrawUnprocessableEntityCode int = 422

/*
PostAPIUserBalanceWithdrawUnprocessableEntity Invalid order number

swagger:response postApiUserBalanceWithdrawUnprocessableEntity
*/
type PostAPIUserBalanceWithdrawUnprocessableEntity struct {
}

// NewPostAPIUserBalanceWithdrawUnprocessableEntity creates PostAPIUserBalanceWithdrawUnprocessableEntity with default headers values
func NewPostAPIUserBalanceWithdrawUnprocessableEntity() *PostAPIUserBalanceWithdrawUnprocessableEntity {

	return &PostAPIUserBalanceWithdrawUnprocessableEntity{}
}

// WriteResponse to the client
func (o *PostAPIUserBalanceWithdrawUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}

// PostAPIUserBalanceWithdrawInternalServerErrorCode is the HTTP code returned for type PostAPIUserBalanceWithdrawInternalServerError
const PostAPIUserBalanceWithdrawInternalServerErrorCode int = 500

/*
PostAPIUserBalanceWithdrawInternalServerError Internal server error

swagger:response postApiUserBalanceWithdrawInternalServerError
*/
type PostAPIUserBalanceWithdrawInternalServerError struct {
}

// NewPostAPIUserBalanceWithdrawInternalServerError creates PostAPIUserBalanceWithdrawInternalServerError with default headers values
func NewPostAPIUserBalanceWithdrawInternalServerError() *PostAPIUserBalanceWithdrawInternalServerError {

	return &PostAPIUserBalanceWithdrawInternalServerError{}
}

// WriteResponse to the client
func (o *PostAPIUserBalanceWithdrawInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
