// Code generated by go-swagger; DO NOT EDIT.

package balance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostAPIUserBalanceWithdrawHandlerFunc turns a function with the right signature into a post API user balance withdraw handler
type PostAPIUserBalanceWithdrawHandlerFunc func(PostAPIUserBalanceWithdrawParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAPIUserBalanceWithdrawHandlerFunc) Handle(params PostAPIUserBalanceWithdrawParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostAPIUserBalanceWithdrawHandler interface for that can handle valid post API user balance withdraw params
type PostAPIUserBalanceWithdrawHandler interface {
	Handle(PostAPIUserBalanceWithdrawParams, interface{}) middleware.Responder
}

// NewPostAPIUserBalanceWithdraw creates a new http.Handler for the post API user balance withdraw operation
func NewPostAPIUserBalanceWithdraw(ctx *middleware.Context, handler PostAPIUserBalanceWithdrawHandler) *PostAPIUserBalanceWithdraw {
	return &PostAPIUserBalanceWithdraw{Context: ctx, Handler: handler}
}

/*
	PostAPIUserBalanceWithdraw swagger:route POST /api/user/balance/withdraw Balance postApiUserBalanceWithdraw

Withdraw funds from balance
*/
type PostAPIUserBalanceWithdraw struct {
	Context *middleware.Context
	Handler PostAPIUserBalanceWithdrawHandler
}

func (o *PostAPIUserBalanceWithdraw) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAPIUserBalanceWithdrawParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
