// Code generated by go-swagger; DO NOT EDIT.

package balance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/DanilNaum/gophermarket/internal/api/models"
)

// NewPostAPIUserBalanceWithdrawParams creates a new PostAPIUserBalanceWithdrawParams object
//
// There are no default values defined in the spec.
func NewPostAPIUserBalanceWithdrawParams() PostAPIUserBalanceWithdrawParams {

	return PostAPIUserBalanceWithdrawParams{}
}

// PostAPIUserBalanceWithdrawParams contains all the bound params for the post API user balance withdraw operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostAPIUserBalanceWithdraw
type PostAPIUserBalanceWithdrawParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Body *models.WithdrawalRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostAPIUserBalanceWithdrawParams() beforehand.
func (o *PostAPIUserBalanceWithdrawParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.WithdrawalRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
