// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAPIUserLoginOKCode is the HTTP code returned for type PostAPIUserLoginOK
const PostAPIUserLoginOKCode int = 200

/*
PostAPIUserLoginOK User successfully authenticated

swagger:response postApiUserLoginOK
*/
type PostAPIUserLoginOK struct {
	/*Authorization token

	 */
	Authorization string `json:"Authorization"`
	/*Session cookie

	 */
	SetCookie string `json:"Set-Cookie"`
}

// NewPostAPIUserLoginOK creates PostAPIUserLoginOK with default headers values
func NewPostAPIUserLoginOK() *PostAPIUserLoginOK {

	return &PostAPIUserLoginOK{}
}

// WithAuthorization adds the authorization to the post Api user login o k response
func (o *PostAPIUserLoginOK) WithAuthorization(authorization string) *PostAPIUserLoginOK {
	o.Authorization = authorization
	return o
}

// SetAuthorization sets the authorization to the post Api user login o k response
func (o *PostAPIUserLoginOK) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithSetCookie adds the setCookie to the post Api user login o k response
func (o *PostAPIUserLoginOK) WithSetCookie(setCookie string) *PostAPIUserLoginOK {
	o.SetCookie = setCookie
	return o
}

// SetSetCookie sets the setCookie to the post Api user login o k response
func (o *PostAPIUserLoginOK) SetSetCookie(setCookie string) {
	o.SetCookie = setCookie
}

// WriteResponse to the client
func (o *PostAPIUserLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Authorization

	authorization := o.Authorization
	if authorization != "" {
		rw.Header().Set("Authorization", authorization)
	}

	// response header Set-Cookie

	setCookie := o.SetCookie
	if setCookie != "" {
		rw.Header().Set("Set-Cookie", setCookie)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostAPIUserLoginBadRequestCode is the HTTP code returned for type PostAPIUserLoginBadRequest
const PostAPIUserLoginBadRequestCode int = 400

/*
PostAPIUserLoginBadRequest Invalid request format

swagger:response postApiUserLoginBadRequest
*/
type PostAPIUserLoginBadRequest struct {
}

// NewPostAPIUserLoginBadRequest creates PostAPIUserLoginBadRequest with default headers values
func NewPostAPIUserLoginBadRequest() *PostAPIUserLoginBadRequest {

	return &PostAPIUserLoginBadRequest{}
}

// WriteResponse to the client
func (o *PostAPIUserLoginBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostAPIUserLoginUnauthorizedCode is the HTTP code returned for type PostAPIUserLoginUnauthorized
const PostAPIUserLoginUnauthorizedCode int = 401

/*
PostAPIUserLoginUnauthorized Invalid login/password pair

swagger:response postApiUserLoginUnauthorized
*/
type PostAPIUserLoginUnauthorized struct {
}

// NewPostAPIUserLoginUnauthorized creates PostAPIUserLoginUnauthorized with default headers values
func NewPostAPIUserLoginUnauthorized() *PostAPIUserLoginUnauthorized {

	return &PostAPIUserLoginUnauthorized{}
}

// WriteResponse to the client
func (o *PostAPIUserLoginUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostAPIUserLoginInternalServerErrorCode is the HTTP code returned for type PostAPIUserLoginInternalServerError
const PostAPIUserLoginInternalServerErrorCode int = 500

/*
PostAPIUserLoginInternalServerError Internal server error

swagger:response postApiUserLoginInternalServerError
*/
type PostAPIUserLoginInternalServerError struct {
}

// NewPostAPIUserLoginInternalServerError creates PostAPIUserLoginInternalServerError with default headers values
func NewPostAPIUserLoginInternalServerError() *PostAPIUserLoginInternalServerError {

	return &PostAPIUserLoginInternalServerError{}
}

// WriteResponse to the client
func (o *PostAPIUserLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
