// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostAPIUserRegisterHandlerFunc turns a function with the right signature into a post API user register handler
type PostAPIUserRegisterHandlerFunc func(PostAPIUserRegisterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAPIUserRegisterHandlerFunc) Handle(params PostAPIUserRegisterParams) middleware.Responder {
	return fn(params)
}

// PostAPIUserRegisterHandler interface for that can handle valid post API user register params
type PostAPIUserRegisterHandler interface {
	Handle(PostAPIUserRegisterParams) middleware.Responder
}

// NewPostAPIUserRegister creates a new http.Handler for the post API user register operation
func NewPostAPIUserRegister(ctx *middleware.Context, handler PostAPIUserRegisterHandler) *PostAPIUserRegister {
	return &PostAPIUserRegister{Context: ctx, Handler: handler}
}

/*
	PostAPIUserRegister swagger:route POST /api/user/register User postApiUserRegister

Register a new user
*/
type PostAPIUserRegister struct {
	Context *middleware.Context
	Handler PostAPIUserRegisterHandler
}

func (o *PostAPIUserRegister) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAPIUserRegisterParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
