// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostAPIUserLoginHandlerFunc turns a function with the right signature into a post API user login handler
type PostAPIUserLoginHandlerFunc func(PostAPIUserLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAPIUserLoginHandlerFunc) Handle(params PostAPIUserLoginParams) middleware.Responder {
	return fn(params)
}

// PostAPIUserLoginHandler interface for that can handle valid post API user login params
type PostAPIUserLoginHandler interface {
	Handle(PostAPIUserLoginParams) middleware.Responder
}

// NewPostAPIUserLogin creates a new http.Handler for the post API user login operation
func NewPostAPIUserLogin(ctx *middleware.Context, handler PostAPIUserLoginHandler) *PostAPIUserLogin {
	return &PostAPIUserLogin{Context: ctx, Handler: handler}
}

/*
	PostAPIUserLogin swagger:route POST /api/user/login User postApiUserLogin

Authenticate user
*/
type PostAPIUserLogin struct {
	Context *middleware.Context
	Handler PostAPIUserLoginHandler
}

func (o *PostAPIUserLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAPIUserLoginParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
