// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAPIUserRegisterOKCode is the HTTP code returned for type PostAPIUserRegisterOK
const PostAPIUserRegisterOKCode int = 200

/*
PostAPIUserRegisterOK User successfully registered and authenticated

swagger:response postApiUserRegisterOK
*/
type PostAPIUserRegisterOK struct {
	/*Authorization token

	 */
	Authorization string `json:"Authorization"`
	/*Session cookie

	 */
	SetCookie string `json:"Set-Cookie"`
}

// NewPostAPIUserRegisterOK creates PostAPIUserRegisterOK with default headers values
func NewPostAPIUserRegisterOK() *PostAPIUserRegisterOK {

	return &PostAPIUserRegisterOK{}
}

// WithAuthorization adds the authorization to the post Api user register o k response
func (o *PostAPIUserRegisterOK) WithAuthorization(authorization string) *PostAPIUserRegisterOK {
	o.Authorization = authorization
	return o
}

// SetAuthorization sets the authorization to the post Api user register o k response
func (o *PostAPIUserRegisterOK) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithSetCookie adds the setCookie to the post Api user register o k response
func (o *PostAPIUserRegisterOK) WithSetCookie(setCookie string) *PostAPIUserRegisterOK {
	o.SetCookie = setCookie
	return o
}

// SetSetCookie sets the setCookie to the post Api user register o k response
func (o *PostAPIUserRegisterOK) SetSetCookie(setCookie string) {
	o.SetCookie = setCookie
}

// WriteResponse to the client
func (o *PostAPIUserRegisterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Authorization

	authorization := o.Authorization
	if authorization != "" {
		rw.Header().Set("Authorization", authorization)
	}

	// response header Set-Cookie

	setCookie := o.SetCookie
	if setCookie != "" {
		rw.Header().Set("Set-Cookie", setCookie)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostAPIUserRegisterBadRequestCode is the HTTP code returned for type PostAPIUserRegisterBadRequest
const PostAPIUserRegisterBadRequestCode int = 400

/*
PostAPIUserRegisterBadRequest Invalid request format

swagger:response postApiUserRegisterBadRequest
*/
type PostAPIUserRegisterBadRequest struct {
}

// NewPostAPIUserRegisterBadRequest creates PostAPIUserRegisterBadRequest with default headers values
func NewPostAPIUserRegisterBadRequest() *PostAPIUserRegisterBadRequest {

	return &PostAPIUserRegisterBadRequest{}
}

// WriteResponse to the client
func (o *PostAPIUserRegisterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostAPIUserRegisterConflictCode is the HTTP code returned for type PostAPIUserRegisterConflict
const PostAPIUserRegisterConflictCode int = 409

/*
PostAPIUserRegisterConflict Login already taken

swagger:response postApiUserRegisterConflict
*/
type PostAPIUserRegisterConflict struct {
}

// NewPostAPIUserRegisterConflict creates PostAPIUserRegisterConflict with default headers values
func NewPostAPIUserRegisterConflict() *PostAPIUserRegisterConflict {

	return &PostAPIUserRegisterConflict{}
}

// WriteResponse to the client
func (o *PostAPIUserRegisterConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// PostAPIUserRegisterInternalServerErrorCode is the HTTP code returned for type PostAPIUserRegisterInternalServerError
const PostAPIUserRegisterInternalServerErrorCode int = 500

/*
PostAPIUserRegisterInternalServerError Internal server error

swagger:response postApiUserRegisterInternalServerError
*/
type PostAPIUserRegisterInternalServerError struct {
}

// NewPostAPIUserRegisterInternalServerError creates PostAPIUserRegisterInternalServerError with default headers values
func NewPostAPIUserRegisterInternalServerError() *PostAPIUserRegisterInternalServerError {

	return &PostAPIUserRegisterInternalServerError{}
}

// WriteResponse to the client
func (o *PostAPIUserRegisterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
