// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/DanilNaum/gophermarket/internal/api/restapi/operations/balance"
	"github.com/DanilNaum/gophermarket/internal/api/restapi/operations/orders"
	"github.com/DanilNaum/gophermarket/internal/api/restapi/operations/user"
)

// NewGopherMarketLoyaltySystemAPIAPI creates a new GopherMarketLoyaltySystemAPI instance
func NewGopherMarketLoyaltySystemAPIAPI(spec *loads.Document) *GopherMarketLoyaltySystemAPIAPI {
	return &GopherMarketLoyaltySystemAPIAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),
		TxtConsumer:  runtime.TextConsumer(),

		JSONProducer: runtime.JSONProducer(),

		BalanceGetAPIUserBalanceHandler: balance.GetAPIUserBalanceHandlerFunc(func(params balance.GetAPIUserBalanceParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation balance.GetAPIUserBalance has not yet been implemented")
		}),
		OrdersGetAPIUserOrdersHandler: orders.GetAPIUserOrdersHandlerFunc(func(params orders.GetAPIUserOrdersParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation orders.GetAPIUserOrders has not yet been implemented")
		}),
		BalanceGetAPIUserWithdrawalsHandler: balance.GetAPIUserWithdrawalsHandlerFunc(func(params balance.GetAPIUserWithdrawalsParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation balance.GetAPIUserWithdrawals has not yet been implemented")
		}),
		BalancePostAPIUserBalanceWithdrawHandler: balance.PostAPIUserBalanceWithdrawHandlerFunc(func(params balance.PostAPIUserBalanceWithdrawParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation balance.PostAPIUserBalanceWithdraw has not yet been implemented")
		}),
		UserPostAPIUserLoginHandler: user.PostAPIUserLoginHandlerFunc(func(params user.PostAPIUserLoginParams) middleware.Responder {
			return middleware.NotImplemented("operation user.PostAPIUserLogin has not yet been implemented")
		}),
		OrdersPostAPIUserOrdersHandler: orders.PostAPIUserOrdersHandlerFunc(func(params orders.PostAPIUserOrdersParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation orders.PostAPIUserOrders has not yet been implemented")
		}),
		UserPostAPIUserRegisterHandler: user.PostAPIUserRegisterHandlerFunc(func(params user.PostAPIUserRegisterParams) middleware.Responder {
			return middleware.NotImplemented("operation user.PostAPIUserRegister has not yet been implemented")
		}),

		// Applies when the "Authorization" header is set
		BearerAuthAuth: func(token string) (interface{}, error) {
			return nil, errors.NotImplemented("api key auth (bearerAuth) Authorization from header param [Authorization] has not yet been implemented")
		},
		// Applies when the "Cookie" header is set
		CookieAuthAuth: func(token string) (interface{}, error) {
			return nil, errors.NotImplemented("api key auth (cookieAuth) Cookie from header param [Cookie] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*GopherMarketLoyaltySystemAPIAPI API for user registration, authentication and order management */
type GopherMarketLoyaltySystemAPIAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer
	// TxtConsumer registers a consumer for the following mime types:
	//   - text/plain
	TxtConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// BearerAuthAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	BearerAuthAuth func(string) (interface{}, error)

	// CookieAuthAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Cookie provided in the header
	CookieAuthAuth func(string) (interface{}, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// BalanceGetAPIUserBalanceHandler sets the operation handler for the get API user balance operation
	BalanceGetAPIUserBalanceHandler balance.GetAPIUserBalanceHandler
	// OrdersGetAPIUserOrdersHandler sets the operation handler for the get API user orders operation
	OrdersGetAPIUserOrdersHandler orders.GetAPIUserOrdersHandler
	// BalanceGetAPIUserWithdrawalsHandler sets the operation handler for the get API user withdrawals operation
	BalanceGetAPIUserWithdrawalsHandler balance.GetAPIUserWithdrawalsHandler
	// BalancePostAPIUserBalanceWithdrawHandler sets the operation handler for the post API user balance withdraw operation
	BalancePostAPIUserBalanceWithdrawHandler balance.PostAPIUserBalanceWithdrawHandler
	// UserPostAPIUserLoginHandler sets the operation handler for the post API user login operation
	UserPostAPIUserLoginHandler user.PostAPIUserLoginHandler
	// OrdersPostAPIUserOrdersHandler sets the operation handler for the post API user orders operation
	OrdersPostAPIUserOrdersHandler orders.PostAPIUserOrdersHandler
	// UserPostAPIUserRegisterHandler sets the operation handler for the post API user register operation
	UserPostAPIUserRegisterHandler user.PostAPIUserRegisterHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *GopherMarketLoyaltySystemAPIAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *GopherMarketLoyaltySystemAPIAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *GopherMarketLoyaltySystemAPIAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *GopherMarketLoyaltySystemAPIAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *GopherMarketLoyaltySystemAPIAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *GopherMarketLoyaltySystemAPIAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *GopherMarketLoyaltySystemAPIAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *GopherMarketLoyaltySystemAPIAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *GopherMarketLoyaltySystemAPIAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the GopherMarketLoyaltySystemAPIAPI
func (o *GopherMarketLoyaltySystemAPIAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}
	if o.TxtConsumer == nil {
		unregistered = append(unregistered, "TxtConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BearerAuthAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}
	if o.CookieAuthAuth == nil {
		unregistered = append(unregistered, "CookieAuth")
	}

	if o.BalanceGetAPIUserBalanceHandler == nil {
		unregistered = append(unregistered, "balance.GetAPIUserBalanceHandler")
	}
	if o.OrdersGetAPIUserOrdersHandler == nil {
		unregistered = append(unregistered, "orders.GetAPIUserOrdersHandler")
	}
	if o.BalanceGetAPIUserWithdrawalsHandler == nil {
		unregistered = append(unregistered, "balance.GetAPIUserWithdrawalsHandler")
	}
	if o.BalancePostAPIUserBalanceWithdrawHandler == nil {
		unregistered = append(unregistered, "balance.PostAPIUserBalanceWithdrawHandler")
	}
	if o.UserPostAPIUserLoginHandler == nil {
		unregistered = append(unregistered, "user.PostAPIUserLoginHandler")
	}
	if o.OrdersPostAPIUserOrdersHandler == nil {
		unregistered = append(unregistered, "orders.PostAPIUserOrdersHandler")
	}
	if o.UserPostAPIUserRegisterHandler == nil {
		unregistered = append(unregistered, "user.PostAPIUserRegisterHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *GopherMarketLoyaltySystemAPIAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *GopherMarketLoyaltySystemAPIAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "bearerAuth":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, o.BearerAuthAuth)

		case "cookieAuth":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, o.CookieAuthAuth)

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *GopherMarketLoyaltySystemAPIAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *GopherMarketLoyaltySystemAPIAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		case "text/plain":
			result["text/plain"] = o.TxtConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *GopherMarketLoyaltySystemAPIAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *GopherMarketLoyaltySystemAPIAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the gopher market loyalty system API API
func (o *GopherMarketLoyaltySystemAPIAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *GopherMarketLoyaltySystemAPIAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/user/balance"] = balance.NewGetAPIUserBalance(o.context, o.BalanceGetAPIUserBalanceHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/user/orders"] = orders.NewGetAPIUserOrders(o.context, o.OrdersGetAPIUserOrdersHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/user/withdrawals"] = balance.NewGetAPIUserWithdrawals(o.context, o.BalanceGetAPIUserWithdrawalsHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/user/balance/withdraw"] = balance.NewPostAPIUserBalanceWithdraw(o.context, o.BalancePostAPIUserBalanceWithdrawHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/user/login"] = user.NewPostAPIUserLogin(o.context, o.UserPostAPIUserLoginHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/user/orders"] = orders.NewPostAPIUserOrders(o.context, o.OrdersPostAPIUserOrdersHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/user/register"] = user.NewPostAPIUserRegister(o.context, o.UserPostAPIUserRegisterHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *GopherMarketLoyaltySystemAPIAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *GopherMarketLoyaltySystemAPIAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *GopherMarketLoyaltySystemAPIAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *GopherMarketLoyaltySystemAPIAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *GopherMarketLoyaltySystemAPIAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
